python train.py --dataset=reddit --gpu=0 --lb=1 --k=0.999 >> curve.txt
python train.py --dataset=reddit --gpu=0 --lb=1 --k=0.998 >> curve.txt
python train.py --dataset=reddit --gpu=0 --lb=1 --k=0.996 >> curve.txt
python train.py --dataset=reddit --gpu=0 --lb=1 --k=0.99 >> curve.txt
python train.py --dataset=reddit --gpu=0 --lb=1 --k=0.98 >> curve.txt
python train.py --dataset=reddit --gpu=0 --lb=1 --k=0.96 >> curve.txt
python train.py --dataset=reddit --gpu=0 --lb=1 --k=0.9 >> curve.txt
python train.py --dataset=reddit --gpu=0 --lb=1 --k=0.75 >> curve.txt
python train.py --dataset=reddit --gpu=0 --lb=1 --k=0.5 >> curve.txt